name: Test on Push to Master

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install dependencies
        run: npm ci

      - name: Run tests with Vitest
        run: npm run test

      - name: Set up Python
        uses: actions/setup-python@v4
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pytest pytest-cov selenium
          pip install pytest-playwright

      - name: Install browsers for tests
        run: playwright install

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build image
        run: docker build -t plan-it-web .

      - name: Run PlanIT-Web in a container
        run: docker run -d -p 3000:3000 --name app plan-it-web

      - name: Test with pytest
        run: pytest -v
